### ISSUE TITLE
Support for appDirectory?

### ISSUE THREAD

**Issue by Nettsentrisk** [sergiodxa/remix-define-routes#4]
The file resolver is hard-coded to use /app/ as the base, should be using the value from remix config `appDirectory`.

**Comment by sergiodxa** [comment]
With RRv7 adding the `routes.ts` file and [Remix potentially adding it on v2](https://github.com/remix-run/remix/pull/10107) to help simplify the migration, this package is no longer useful, the `routes.ts` file uses a similar syntax already, so I don't plan to develop this anymore.
